/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects.$projectId.index'
import { Route as ProjectsProjectIdWorkRouteImport } from './routes/projects.$projectId.work'
import { Route as ProjectsProjectIdReportsRouteImport } from './routes/projects.$projectId.reports'
import { Route as ProjectsProjectIdRegisteredRouteImport } from './routes/projects.$projectId.registered'
import { Route as ProjectsProjectIdPaymentsRouteImport } from './routes/projects.$projectId.payments'
import { Route as ProjectsProjectIdInfoRouteImport } from './routes/projects.$projectId.info'
import { Route as ProjectsProjectIdGeneralPaymentsRouteImport } from './routes/projects.$projectId.general-payments'
import { Route as ProjectsProjectIdFilesRouteImport } from './routes/projects.$projectId.files'
import { Route as ProjectsProjectIdCustomersRouteImport } from './routes/projects.$projectId.customers'
import { Route as ProjectsProjectIdCalendarRouteImport } from './routes/projects.$projectId.calendar'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdWorkRoute = ProjectsProjectIdWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdReportsRoute =
  ProjectsProjectIdReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdRegisteredRoute =
  ProjectsProjectIdRegisteredRouteImport.update({
    id: '/registered',
    path: '/registered',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdPaymentsRoute =
  ProjectsProjectIdPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdInfoRoute = ProjectsProjectIdInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdGeneralPaymentsRoute =
  ProjectsProjectIdGeneralPaymentsRouteImport.update({
    id: '/general-payments',
    path: '/general-payments',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdFilesRoute = ProjectsProjectIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdCustomersRoute =
  ProjectsProjectIdCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdCalendarRoute =
  ProjectsProjectIdCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/calendar': typeof ProjectsProjectIdCalendarRoute
  '/projects/$projectId/customers': typeof ProjectsProjectIdCustomersRoute
  '/projects/$projectId/files': typeof ProjectsProjectIdFilesRoute
  '/projects/$projectId/general-payments': typeof ProjectsProjectIdGeneralPaymentsRoute
  '/projects/$projectId/info': typeof ProjectsProjectIdInfoRoute
  '/projects/$projectId/payments': typeof ProjectsProjectIdPaymentsRoute
  '/projects/$projectId/registered': typeof ProjectsProjectIdRegisteredRoute
  '/projects/$projectId/reports': typeof ProjectsProjectIdReportsRoute
  '/projects/$projectId/work': typeof ProjectsProjectIdWorkRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/projects/$projectId/calendar': typeof ProjectsProjectIdCalendarRoute
  '/projects/$projectId/customers': typeof ProjectsProjectIdCustomersRoute
  '/projects/$projectId/files': typeof ProjectsProjectIdFilesRoute
  '/projects/$projectId/general-payments': typeof ProjectsProjectIdGeneralPaymentsRoute
  '/projects/$projectId/info': typeof ProjectsProjectIdInfoRoute
  '/projects/$projectId/payments': typeof ProjectsProjectIdPaymentsRoute
  '/projects/$projectId/registered': typeof ProjectsProjectIdRegisteredRoute
  '/projects/$projectId/reports': typeof ProjectsProjectIdReportsRoute
  '/projects/$projectId/work': typeof ProjectsProjectIdWorkRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/calendar': typeof ProjectsProjectIdCalendarRoute
  '/projects/$projectId/customers': typeof ProjectsProjectIdCustomersRoute
  '/projects/$projectId/files': typeof ProjectsProjectIdFilesRoute
  '/projects/$projectId/general-payments': typeof ProjectsProjectIdGeneralPaymentsRoute
  '/projects/$projectId/info': typeof ProjectsProjectIdInfoRoute
  '/projects/$projectId/payments': typeof ProjectsProjectIdPaymentsRoute
  '/projects/$projectId/registered': typeof ProjectsProjectIdRegisteredRoute
  '/projects/$projectId/reports': typeof ProjectsProjectIdReportsRoute
  '/projects/$projectId/work': typeof ProjectsProjectIdWorkRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/projects/$projectId'
    | '/projects/$projectId/calendar'
    | '/projects/$projectId/customers'
    | '/projects/$projectId/files'
    | '/projects/$projectId/general-payments'
    | '/projects/$projectId/info'
    | '/projects/$projectId/payments'
    | '/projects/$projectId/registered'
    | '/projects/$projectId/reports'
    | '/projects/$projectId/work'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/projects/$projectId/calendar'
    | '/projects/$projectId/customers'
    | '/projects/$projectId/files'
    | '/projects/$projectId/general-payments'
    | '/projects/$projectId/info'
    | '/projects/$projectId/payments'
    | '/projects/$projectId/registered'
    | '/projects/$projectId/reports'
    | '/projects/$projectId/work'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/projects/$projectId'
    | '/projects/$projectId/calendar'
    | '/projects/$projectId/customers'
    | '/projects/$projectId/files'
    | '/projects/$projectId/general-payments'
    | '/projects/$projectId/info'
    | '/projects/$projectId/payments'
    | '/projects/$projectId/registered'
    | '/projects/$projectId/reports'
    | '/projects/$projectId/work'
    | '/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/work': {
      id: '/projects/$projectId/work'
      path: '/work'
      fullPath: '/projects/$projectId/work'
      preLoaderRoute: typeof ProjectsProjectIdWorkRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/reports': {
      id: '/projects/$projectId/reports'
      path: '/reports'
      fullPath: '/projects/$projectId/reports'
      preLoaderRoute: typeof ProjectsProjectIdReportsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/registered': {
      id: '/projects/$projectId/registered'
      path: '/registered'
      fullPath: '/projects/$projectId/registered'
      preLoaderRoute: typeof ProjectsProjectIdRegisteredRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/payments': {
      id: '/projects/$projectId/payments'
      path: '/payments'
      fullPath: '/projects/$projectId/payments'
      preLoaderRoute: typeof ProjectsProjectIdPaymentsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/info': {
      id: '/projects/$projectId/info'
      path: '/info'
      fullPath: '/projects/$projectId/info'
      preLoaderRoute: typeof ProjectsProjectIdInfoRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/general-payments': {
      id: '/projects/$projectId/general-payments'
      path: '/general-payments'
      fullPath: '/projects/$projectId/general-payments'
      preLoaderRoute: typeof ProjectsProjectIdGeneralPaymentsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/files': {
      id: '/projects/$projectId/files'
      path: '/files'
      fullPath: '/projects/$projectId/files'
      preLoaderRoute: typeof ProjectsProjectIdFilesRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/customers': {
      id: '/projects/$projectId/customers'
      path: '/customers'
      fullPath: '/projects/$projectId/customers'
      preLoaderRoute: typeof ProjectsProjectIdCustomersRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/calendar': {
      id: '/projects/$projectId/calendar'
      path: '/calendar'
      fullPath: '/projects/$projectId/calendar'
      preLoaderRoute: typeof ProjectsProjectIdCalendarRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdCalendarRoute: typeof ProjectsProjectIdCalendarRoute
  ProjectsProjectIdCustomersRoute: typeof ProjectsProjectIdCustomersRoute
  ProjectsProjectIdFilesRoute: typeof ProjectsProjectIdFilesRoute
  ProjectsProjectIdGeneralPaymentsRoute: typeof ProjectsProjectIdGeneralPaymentsRoute
  ProjectsProjectIdInfoRoute: typeof ProjectsProjectIdInfoRoute
  ProjectsProjectIdPaymentsRoute: typeof ProjectsProjectIdPaymentsRoute
  ProjectsProjectIdRegisteredRoute: typeof ProjectsProjectIdRegisteredRoute
  ProjectsProjectIdReportsRoute: typeof ProjectsProjectIdReportsRoute
  ProjectsProjectIdWorkRoute: typeof ProjectsProjectIdWorkRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdCalendarRoute: ProjectsProjectIdCalendarRoute,
  ProjectsProjectIdCustomersRoute: ProjectsProjectIdCustomersRoute,
  ProjectsProjectIdFilesRoute: ProjectsProjectIdFilesRoute,
  ProjectsProjectIdGeneralPaymentsRoute: ProjectsProjectIdGeneralPaymentsRoute,
  ProjectsProjectIdInfoRoute: ProjectsProjectIdInfoRoute,
  ProjectsProjectIdPaymentsRoute: ProjectsProjectIdPaymentsRoute,
  ProjectsProjectIdRegisteredRoute: ProjectsProjectIdRegisteredRoute,
  ProjectsProjectIdReportsRoute: ProjectsProjectIdReportsRoute,
  ProjectsProjectIdWorkRoute: ProjectsProjectIdWorkRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
